apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: openshift-nfs-storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: <PROVISIONER NAME>
            - name: NFS_SERVER
              value: <IP OR HOSTNAME NFS SERVER>
            - name: NFS_PATH
              value: <NFS EXPORTS DIRECTORY PATH>
      volumes:
        - name: nfs-client-root
          nfs:
            server: <IP OR HOSTNAME NFS SERVER>
            path: <NFS EXPORTS DIRECTORY PATH>
